apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle-area-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circle-area
  template:
    metadata:
      labels:
        app: circle-area
    spec:
      containers:
      - name: circle-area-container
        image: username/circle-area:1.0
